import React from 'react';
import '../styles/globals.css';
import NavBar from '@/components/NavBar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <NavBar/>
        <main> 
      
          {children}
       
          </main>
      </body>
    </html>
  );
}